Feat/upgradability
felixprotocol/felix-contracts pull request #2
Opened 2024-10-02 16:24 UTC by auditsbydanny

2024-10-02 21:16 UTC, 0x73696d616f requested changes
Looking good, nice work on the assembly.
Some additional stuff
1. TroveNft and metadataNFT should be upgradeable
2. Add to the readme that we remove immutable vars to not assign some variables in the constructor and others in the initialize()
3. Add to the readme that forge inspect does not work for some reason and needs to be brute forced. But let's keep the contracts as is, forge inspect should only be called now and if we change the code in the future.
4. Let's add some tests to test upgrade with reinitializer() for each contract and change ownership in the ones with ownership

2024-10-02 21:16 UTC, 0x73696d616f commented on contracts/src/Dependencies/AddRemoveManagers.sol
> +abstract contract AddRemoveManagers is Initializable, IAddRemoveManagers {
No need to make this abstracts

2024-10-02 21:16 UTC, 0x73696d616f commented on contracts/src/Dependencies/LiquityBase.sol
> +abstract contract LiquityBase is Initializable, ILiquityBase {
No need abstract

2024-10-02 21:16 UTC, 0x73696d616f commented on contracts/src/Libraries/BorrowerOperationsInit.sol
> +            address troveNFT = address(_addressesRegistry.troveNFT());
Missing event, let's place this one into a lib just like LiquityBaseInit to remove duplication

2024-10-02 21:16 UTC, 0x73696d616f commented on contracts/src/Libraries/BorrowerOperationsInit.sol
> +        {
The order here is different than the original one in the constructor, let's use the same order of vars to make it easier to debug

2024-10-02 21:16 UTC, 0x73696d616f commented on contracts/src/Libraries/LiquityBaseInit.sol
> +            let mask := not(shl(mul(ACTIVE_POOL_OFFSET, 8), sub(shl(20, 1), 1)))
add 1 comment saying storage variables are written from right to left
ex: `uint8 public var = 1;` becomes 0x00...01

2024-10-02 21:16 UTC, 0x73696d616f commented on contracts/src/Zappers/GasCompZapper.sol
> -contract GasCompZapper is AddRemoveManagers {
missing gap

2024-10-02 21:16 UTC, 0x73696d616f commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        return abi.encodePacked(type(TransparentUpgradeableProxy).creationCode, abi.encode(_impl, _admin, ""));
"" should be replaced by initialization data

2024-10-02 21:16 UTC, 0x73696d616f commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        r.hintHelpers = HintHelpers(address(new TransparentUpgradeableProxy(address(hintHelpersImpl), address(proxyAdmin), "")));
let's initialize in the constructor with the initialization data to make it atomic

2024-10-02 21:16 UTC, 0x73696d616f commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        r.multiTroveGetter = MultiTroveGetter(address(new TransparentUpgradeableProxy(
let's create a helper function to deploy the proxy with the implementation and the initialize data
will help reduce duplication a bit

2024-10-02 21:16 UTC, 0x73696d616f commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        SALT = keccak256(abi.encodePacked(block.timestamp, address(_addressesRegistry)));
SALT should be the original one, will work if we set the initialize arguments in the proxy

2024-10-02 21:16 UTC, 0x73696d616f commented on contracts/src/test/deployment.t.sol
> +   function testBorrowerOperationsInitialized() public view {
let's test the other upgradeable contracts too

2024-10-03 10:08 UTC, auditsbydanny commented on contracts/src/Dependencies/AddRemoveManagers.sol
> +abstract contract AddRemoveManagers is Initializable, IAddRemoveManagers {
Fixed in `a177249aa0db6de2a4a68bcd7ddd85f59b453da9`

2024-10-03 10:08 UTC, auditsbydanny commented on contracts/src/Dependencies/LiquityBase.sol
> +abstract contract LiquityBase is Initializable, ILiquityBase {
Fixed in `a177249aa0db6de2a4a68bcd7ddd85f59b453da9`

2024-10-03 11:09 UTC, auditsbydanny commented on contracts/src/Libraries/BorrowerOperationsInit.sol
> +            address troveNFT = address(_addressesRegistry.troveNFT());
Fixed in `6bddd9edaefcde040a584f9b4f298f3e2b95ea52`

2024-10-03 11:09 UTC, auditsbydanny commented on contracts/src/Libraries/BorrowerOperationsInit.sol
> +        {
Fixed in `6bddd9edaefcde040a584f9b4f298f3e2b95ea52`

2024-10-03 11:09 UTC, auditsbydanny commented on contracts/src/Libraries/LiquityBaseInit.sol
> +            let mask := not(shl(mul(ACTIVE_POOL_OFFSET, 8), sub(shl(20, 1), 1)))
Fixed in `6bddd9edaefcde040a584f9b4f298f3e2b95ea52`

2024-10-03 11:29 UTC, auditsbydanny commented on contracts/src/Zappers/GasCompZapper.sol
> -contract GasCompZapper is AddRemoveManagers {
Fixed in `0302acdfe06290770603f0a13a394ee9497f81fa`

2024-10-03 14:29 UTC, auditsbydanny commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        return abi.encodePacked(type(TransparentUpgradeableProxy).creationCode, abi.encode(_impl, _admin, ""));
Fixed in `d23e391f3697654901994020bffff25fd197614e`

2024-10-03 14:29 UTC, auditsbydanny commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        r.hintHelpers = HintHelpers(address(new TransparentUpgradeableProxy(address(hintHelpersImpl), address(proxyAdmin), "")));
Fixed in `d23e391f3697654901994020bffff25fd197614e`

2024-10-03 14:29 UTC, auditsbydanny commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        r.multiTroveGetter = MultiTroveGetter(address(new TransparentUpgradeableProxy(
Fixed in `d23e391f3697654901994020bffff25fd197614e`

2024-10-03 14:29 UTC, auditsbydanny commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        SALT = keccak256(abi.encodePacked(block.timestamp, address(_addressesRegistry)));
Fixed in `d23e391f3697654901994020bffff25fd197614e`

2024-10-03 16:11 UTC, merged