Chore/hl testnet deploy
felixprotocol/felix-contracts pull request #3
Opened 2024-10-04 12:51 UTC by auditsbydanny

2024-10-08 11:56 UTC, 0x73696d616f requested changes
Some extra stuff besides the comments:
1. Let's make the BoldToken upgradeble and adjust the script.
2. Let's also make the mockInterestRouter upgradeable, so we can update it later.
3. And also make a setter for the `SP_YIELD_SPLIT` because we might change it. It's easier than making an upgrade just to change a var we know will change.

2024-10-08 11:56 UTC, 0x73696d616f commented on contracts/src/scripts/DeployLiquity2.s.sol
>          troveManagerParamsArray[0] = TroveManagerParams(150e16, 110e16, 110e16, 5e16, 10e16); // WETH
Let's place these in the constants

2024-10-08 11:56 UTC, 0x73696d616f commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        if (block.chainid != 0 && vm.envOr("OPEN_DEMO_TROVES", false)) {
You can return early here instead, looks better.
`If (block.chainid == 0 || !vm.envOr("OPEN_DEMO_TROVES", false) return;`

2024-10-08 11:56 UTC, 0x73696d616f commented on contracts/src/scripts/DeployLiquity2.s.sol
> +            WETH = IWETH(0x1BCDCe8101EE46d960BF0A1E55548542BD4008D1);
Move to constant files

2024-10-08 11:56 UTC, 0x73696d616f commented on contracts/src/scripts/DeployLiquity2.s.sol
> +            vars.collaterals[1] = IERC20Metadata(0xae78736Cd615f374D3085123A210448E74Fc6393); // RETH
Move to constants files

2024-10-08 11:56 UTC, 0x73696d616f commented on contracts/src/scripts/DeployLiquity2.s.sol
> +                demoTroves[0] = DemoTroveParams(1, demoAccounts[0], 0, 21e18, 2000e18, 3.3e16);
Why is this 0? should be 8 right?

2024-10-08 11:56 UTC, 0x73696d616f commented on contracts/src/scripts/DeployLiquity2.s.sol
> +    uint256 constant HL_ETH_FEED_L1_INDEX = 4;
Move to constants file

2024-10-08 11:56 UTC, 0x73696d616f commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        if (block.chainid == 0) {
Let's place the mainnet chain id in the constants file

2024-10-08 11:56 UTC, 0x73696d616f commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        if (block.chainid == 998) {
Let's not leave TODO's, think this should have a flag too, `USE_MOCK_ORACLE` or smth.
If the chain id is mainnet, or `USE_MOCK_ORACLE` is false, use the hl oracle
else use the mock oracle

2024-10-10 08:41 UTC, auditsbydanny commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        if (block.chainid == 998) {
Resolved in [2a74157](https://github.com/threesigmaxyz/bold/pull/3/commits/2a74157125ba6563ffba9ba2cb4cb162ac1fc8fc)

2024-10-10 08:41 UTC, auditsbydanny commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        if (block.chainid == 0) {
[2a74157](https://github.com/threesigmaxyz/bold/pull/3/commits/2a74157125ba6563ffba9ba2cb4cb162ac1fc8fc)

2024-10-10 08:42 UTC, auditsbydanny commented on contracts/src/scripts/DeployLiquity2.s.sol
> +                demoTroves[0] = DemoTroveParams(1, demoAccounts[0], 0, 21e18, 2000e18, 3.3e16);
Resolved in [2a74157](https://github.com/threesigmaxyz/bold/pull/3/commits/2a74157125ba6563ffba9ba2cb4cb162ac1fc8fc)

2024-10-10 08:42 UTC, auditsbydanny commented on contracts/src/scripts/DeployLiquity2.s.sol
> +            vars.collaterals[1] = IERC20Metadata(0xae78736Cd615f374D3085123A210448E74Fc6393); // RETH
Resolved in [2a74157](https://github.com/threesigmaxyz/bold/pull/3/commits/2a74157125ba6563ffba9ba2cb4cb162ac1fc8fc)

2024-10-10 08:42 UTC, auditsbydanny commented on contracts/src/scripts/DeployLiquity2.s.sol
> +            WETH = IWETH(0x1BCDCe8101EE46d960BF0A1E55548542BD4008D1);
Resolved in [2a74157](https://github.com/threesigmaxyz/bold/pull/3/commits/2a74157125ba6563ffba9ba2cb4cb162ac1fc8fc)

2024-10-10 08:42 UTC, auditsbydanny commented on contracts/src/scripts/DeployLiquity2.s.sol
> +        if (block.chainid != 0 && vm.envOr("OPEN_DEMO_TROVES", false)) {
Resolved in [2a74157](https://github.com/threesigmaxyz/bold/pull/3/commits/2a74157125ba6563ffba9ba2cb4cb162ac1fc8fc)

2024-10-10 08:42 UTC, auditsbydanny commented on contracts/src/scripts/DeployLiquity2.s.sol
>          troveManagerParamsArray[0] = TroveManagerParams(150e16, 110e16, 110e16, 5e16, 10e16); // WETH
Resolved in [2a74157](https://github.com/threesigmaxyz/bold/pull/3/commits/2a74157125ba6563ffba9ba2cb4cb162ac1fc8fc)

2024-10-10 08:47 UTC, auditsbydanny commented on contracts/src/scripts/DeployLiquity2.s.sol
> +    uint256 constant HL_ETH_FEED_L1_INDEX = 4;
Resolved in [6719602](https://github.com/threesigmaxyz/bold/pull/3/commits/6719602a88eaefd363ea0fa6ae72c55ec825f861)

2024-10-10 12:27 UTC, merged